---
kind: pipeline
type: docker
name: default

steps:
- name: hello1
  image: busybox
  commands:
  - echo "hello world";
  - export NODE_ENV=testing;
  - echo "$NODE_ENV";
  - echo "This is example file" >> example.txt
  - ls -al
  - echo "DOCKER_REGISTRY_USERNAME=${DOCKER_REGISTRY_USERNAME}";
  - echo "DOCKER_REGISTRY_PASSWORD=${DOCKER_REGISTRY_PASSWORD}"
  
- name: hello2
  image: busybox
  commands:
  - echo "thank you";
  - echo "$NODE_ENV";
  - ls -al
  - cat example.txt
  - echo "DOCKER_REGISTRY_USERNAME=$(DOCKER_REGISTRY_USERNAME)";
  - echo "DOCKER_REGISTRY_PASSWORD=$(DOCKER_REGISTRY_PASSWORD)"
 
trigger:
  branch:
  - main
