---
kind: pipeline
type: docker
name: default

steps:
- name: hello1
  image: busybox
  commands:
  - echo "hello world";
  - export NODE_ENV=testing;
  - echo "$NODE_ENV";
  - echo "This is example file" >> example.txt
  - ls -al
  - echo "DOCKER_REGISTRY_USERNAME=${DOCKER_REGISTRY_USERNAME}";
  - echo "DOCKER_REGISTRY_PASSWORD=${DOCKER_REGISTRY_PASSWORD}"
  - echo "DOCKER_REGISTRY_USERNAME=$DOCKER_REGISTRY_USERNAME";
  - echo "DOCKER_REGISTRY_PASSWORD=$DOCKER_REGISTRY_PASSWORD";
  - export IMAGE_TAG="$([[ ! -z "$DRONE_BUILD_PARENT" && "$DRONE_BUILD_PARENT" -gt 0 ]] && echo "$DRONE_SOURCE_BRANCH-build.$DRONE_BUILD_PARENT" || echo "$DRONE_SOURCE_BRANCH")";
  - echo $IMAGE_TAG;
  environment:
    DOCKER_REGISTRY_USERNAME:
      from_secret: DOCKER_REGISTRY_USERNAME
    DOCKER_REGISTRY_PASSWORD:
      from_secret: DOCKER_REGISTRY_PASSWORD
  
- name: hello2
  image: busybox
  commands:
  - echo "thank you";
  - echo "$NODE_ENV";
  - ls -al
  - cat example.txt
  - echo "DOCKER_REGISTRY_USERNAME=$(DOCKER_REGISTRY_USERNAME)";
  - echo "DOCKER_REGISTRY_PASSWORD=$(DOCKER_REGISTRY_PASSWORD)";
  environment:
    DOCKER_REGISTRY_USERNAME:
      from_secret: DOCKER_REGISTRY_USERNAME
    DOCKER_REGISTRY_PASSWORD:
      from_secret: DOCKER_REGISTRY_PASSWORD
 
trigger:
  branch:
  - main
